Add go language
nichtraunzer/terrarium pull request #33
Opened 2024-04-26 13:07 UTC by terra-naut

add support for go language to container

2024-04-26 13:07 UTC, terra-naut commented
@tbugfinder

2024-04-26 14:04 UTC, tbugfinder requested changes

2024-04-26 14:04 UTC, tbugfinder commented on terraform/docker/Dockerfile.terrarium
> +    # Install GO
Shouldn't be indented...

2024-05-16 11:18 UTC, terra-naut commented on terraform/docker/Dockerfile.terrarium
> +    # Install GO
fixed

2024-05-29 14:21 UTC, tbugfinder approved these changes
ok

2024-05-29 14:27 UTC, merged